/*
===============================================================================
Retail Intelligence Business Analytics

File        : 03_business_analysis.sql
Author      :  Akshay Kumar

Description:
This script performs business-oriented SQL analysis on the cleaned retail
dataset to answer key business questions related to sales performance,
profitability, customer behavior, product performance, and regional trends.

Business Objectives:
1. Evaluate overall business performance.
2. Analyze product category performance.
3. Identify top-performing products and customers.
4. Compare regional and market performance.
5. Evaluate customer segment contribution.
6. Analyze discounting strategy.
7. Measure the impact of loss-making orders.

Purpose:
The insights generated from these SQL queries support business decision-making
and complement the interactive Power BI dashboard.

===============================================================================
*/


/*=============================================================================
Objective:
Calculate overall business performance by measuring total sales,
total profit, and total quantity sold across all retail transactions.
=============================================================================*/

SELECT
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit,
    SUM(quantity) AS total_quantity
FROM orders;



/*=============================================================================
Query 2 : Sales by Category
Objective:
Compare product categories based on total sales to identify the
highest revenue-generating category.
=============================================================================*/

SELECT
    category,
    ROUND(SUM(sales),2) AS total_sales
FROM orders
GROUP BY category
ORDER BY total_sales DESC;



/*=============================================================================
Query 3 : Profit by Category
Objective:
Evaluate the profitability of each product category to identify
the most profitable business segment.
=============================================================================*/

SELECT
    category,
    ROUND(SUM(profit),2) AS total_profit
FROM orders
GROUP BY category
ORDER BY total_profit DESC;



/*=============================================================================
Query 4 : Top 10 Products by Sales
Identify the top ten products generating the highest sales revenue
to understand product-level business performance.
=============================================================================*/

SELECT
    product_name,
    ROUND(SUM(sales),2) AS total_sales
FROM orders
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;



/*=============================================================================
Query 5 : Top 10 Customers by Sales
Objective:
Identify customers contributing the highest sales revenue to support
customer value analysis.
=============================================================================*/

SELECT
    customer_name,
    ROUND(SUM(sales),2) AS total_sales
FROM orders
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;



/*=============================================================================
Query 6 : Regional Sales Performance
Objective:
Compare sales performance across different regions to identify
high-performing geographic markets.
=============================================================================*/

SELECT
    region,
    ROUND(SUM(sales),2) AS total_sales
FROM orders
GROUP BY region
ORDER BY total_sales DESC;



/*=============================================================================
Query 7 : Market-wise Sales
Objective:
Analyze sales contribution from each global market to understand
international business performance.
=============================================================================*/

SELECT
    market,
    ROUND(SUM(sales),2) AS total_sales
FROM orders
GROUP BY market
ORDER BY total_sales DESC;



/*=============================================================================
Query 8 : Customer Segment Performance
Objective:
Evaluate sales and profit generated by each customer segment to
understand segment-wise business contribution.
=============================================================================*/

SELECT
    segment,
    ROUND(SUM(sales),2) AS total_sales,
    ROUND(SUM(profit),2) AS total_profit
FROM orders
GROUP BY segment
ORDER BY total_sales DESC;



/*=============================================================================
Query 9 : Average Discount by Category
Objective:
Compare average discounts offered across product categories to
evaluate pricing and discount strategies.
=============================================================================*/

SELECT
    category,
    ROUND(AVG(discount),2) AS average_discount
FROM orders
GROUP BY category
ORDER BY average_discount DESC;



/*=============================================================================
Query 10 : Loss Making Orders
Objective:
Determine the number of transactions that resulted in negative
profit to assess the extent of loss-making orders.
=============================================================================*/

SELECT
    COUNT(*) AS loss_orders
FROM orders
WHERE profit < 0;


/*===============================================================================
Business Analysis Completed Successfully

The SQL analysis provides valuable business insights into sales,
profitability, customer behavior, product performance, and regional
trends. These insights directly support the Power BI dashboard and
serve as a foundation for data-driven business decisions.

===============================================================================*/